# Generated by Django 4.1.7 on 2023-03-14 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('anos_de_existencia', models.IntegerField()),
                ('popular_no_brasil', models.BooleanField()),
                ('instrumento_mais_usado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('email_contato', models.EmailField(max_length=254)),
                ('pais_origem', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data_criacao', models.DateField()),
                ('num_albuns', models.IntegerField()),
                ('faz_musicas_ainda', models.BooleanField()),
                ('estilo_musical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.estilo')),
                ('musicos', models.ManyToManyField(to='music.musico')),
            ],
        ),
    ]
