# Generated by Django 4.1.7 on 2023-03-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musico',
            name='genero',
            field=models.CharField(default='teste', max_length=10),
            preserve_default=False,
        ),
    ]
